---
language: python
python: 2.7
cache: pip

before_install:
  - sudo apt-get install shellcheck
  - pip install -U -r test-requirements.txt
  - git clone https://github.com/IBM/pattern-ci

before script:
  - "./pattern-ci/tests/shellcheck-lint.sh"
  - "./pattern-ci/tests/yaml-lint.sh"

jobs:
  include:
    - install: ./pattern-ci/scripts/install-minikube.sh
      script: ./tests/deploy-minikube.sh
