apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: db-circuit
  namespace: default
spec:
  destination: 
    name: cloudant-service
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      httpMaxPendingRequests: 1
      httpConsecutiveErrors: 1
      sleepWindow: 15m
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100
