apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: cloudant-delay
  namespace: default
spec:
  destination: 
    name: cloudant-service
  httpFault:
    delay:
      percent: 100
      fixedDelay: 1.1s
