apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: timeout
  namespace: default
spec:
  destination: 
    name: vote-service
  httpReqTimeout:
    simpleTimeout:
      timeout: 1s
      
